In [55]:
# Import modules
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
from pathlib import Path
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

In [56]:
file_path = Path("../Resources/cleaned_data2.csv")
df= pd.read_csv(file_path)

In [57]:
# Create new columns and check if 'delivery', 'pickup', or 'restaurant_reservation' is in 'transactions'
df['delivery'] = df['transactions'].str.contains('delivery', case=False, na=False)
df['pickup'] = df['transactions'].str.contains('pickup', case=False, na=False)
df['restaurant_reservation'] = df['transactions'].str.contains('restaurant_reservation', case=False, na=False)

# Fill NaN values with False in the new columns
df['delivery'] = df['delivery'].fillna(False)
df['pickup'] = df['pickup'].fillna(False)
df['restaurant_reservation'] = df['restaurant_reservation'].fillna(False)

In [58]:
def is_success(rating):
    return rating > 3.7

# Create a new 'success' column based on the 'rating' column
df['success'] = df['rating'].apply(is_success)

df.head()

,id,name,image_url,is_closed,url,review_count,rating,transactions,price,group_city,cuisines,latitude,longitude,state,delivery,pickup,restaurant_reservation,success
0,a0IET3_yCFcO36OqGSsisg,Eataly NYC Flatiron,https://s3-media4.fl.yelpcdn.com/bphoto/1UDlnu...,False,https://www.yelp.com/biz/eataly-nyc-flatiron-n...,6102,4.0,"delivery, pickup",2,New York City,Italian,40.742101,-73.989922,NY,True,True,False,True
1,zj8Lq1T8KIC5zwFief15jg,Prince Street Pizza,https://s3-media4.fl.yelpcdn.com/bphoto/PfI8oV...,False,https://www.yelp.com/biz/prince-street-pizza-n...,5031,4.5,"delivery, pickup",1,New York City,Italian,40.723088,-73.994530,NY,True,True,False,True
2,16ZnHpuaaBt92XWeJHCC5A,Olio e Più,https://s3-media4.fl.yelpcdn.com/bphoto/CUpPgz...,False,https://www.yelp.com/biz/olio-e-pi%C3%B9-new-y...,4858,4.5,"delivery, pickup",2,New York City,Italian,40.733798,-73.999774,NY,True,True,False,True
3,vyoA8dxwScuMV_AsTcjQcg,L & B Spumoni Gardens,https://s3-media1.fl.yelpcdn.com/bphoto/hN5xKw...,False,https://www.yelp.com/biz/l-and-b-spumoni-garde...,4647,4.0,"delivery, pickup",2,New York City,Italian,40.594715,-73.981316,NY,True,True,False,True
4,22nKUyCIbpnzR6R3_g1ptQ,Carmine's Italian Restaurant - Times Square,https://s3-media1.fl.yelpcdn.com/bphoto/0UszeE...,False,https://www.yelp.com/biz/carmines-italian-rest...,4644,4.0,"delivery, pickup",2,New York City,Italian,40.757498,-73.986653,NY,True,True,False,True

In [59]:
y = df['success']
x = df.drop(columns=['rating', 'success','image_url', 'url','name', 'id', 'transactions', 'is_closed'])
#X = df.drop(columns='rating')
x.head()

,review_count,price,group_city,cuisines,latitude,longitude,state,delivery,pickup,restaurant_reservation
0,6102,2,New York City,Italian,40.742101,-73.989922,NY,True,True,False
1,5031,1,New York City,Italian,40.723088,-73.994530,NY,True,True,False
2,4858,2,New York City,Italian,40.733798,-73.999774,NY,True,True,False
3,4647,2,New York City,Italian,40.594715,-73.981316,NY,True,True,False
4,4644,2,New York City,Italian,40.757498,-73.986653,NY,True,True,False

In [60]:
from sklearn import preprocessing
from sklearn import utils

lab = preprocessing.LabelEncoder()
y_transformed = lab.fit_transform(y)

In [61]:
X= x.fillna(0)

In [62]:
X.head()

,review_count,price,group_city,cuisines,latitude,longitude,state,delivery,pickup,restaurant_reservation
0,6102,2,New York City,Italian,40.742101,-73.989922,NY,True,True,False
1,5031,1,New York City,Italian,40.723088,-73.994530,NY,True,True,False
2,4858,2,New York City,Italian,40.733798,-73.999774,NY,True,True,False
3,4647,2,New York City,Italian,40.594715,-73.981316,NY,True,True,False
4,4644,2,New York City,Italian,40.757498,-73.986653,NY,True,True,False

In [63]:
X =pd.get_dummies(X)

In [64]:
X.head()

,review_count,price,latitude,longitude,delivery,pickup,restaurant_reservation,group_city_Albuquerque,group_city_Arlington,group_city_Atlanta,...,state_ON,state_OR,state_PA,state_PE,state_SC,state_TN,state_TX,state_VA,state_WA,state_WI
0,6102,2,40.742101,-73.989922,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,5031,1,40.723088,-73.994530,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,4858,2,40.733798,-73.999774,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,4647,2,40.594715,-73.981316,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4644,2,40.757498,-73.986653,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [65]:
X.dtypes

review_count      int64
price             int64
latitude        float64
longitude       float64
delivery           bool
                 ...
state_TN           bool
state_TX           bool
state_VA           bool
state_WA           bool
state_WI           bool
Length: 102, dtype: object

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, random_state=42)

In [67]:
scaler = StandardScaler()

X_scaler = scaler.fit(X_train)

X_train_scaled = X_scaler.transform(X_train)

X_test_scaled = X_scaler.transform(X_test)

In [68]:
## K Nearest Neighbor method
from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=50)

knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=50)

In [69]:
y_pred = knn.predict(X_test_scaled)

In [70]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      0.62      0.61      2892
           1       0.62      0.59      0.61      2995

    accuracy                           0.61      5887
   macro avg       0.61      0.61      0.61      5887
weighted avg       0.61      0.61      0.61      5887

In [71]:
from sklearn.neighbors import KNeighborsRegressor


knn2 = KNeighborsRegressor(n_neighbors=50)

knn2.fit(X_train_scaled, y_train)

KNeighborsRegressor(n_neighbors=50)

In [72]:
y_pred2 = knn2.predict(X_test_scaled)

In [73]:
from sklearn import metrics
import numpy as np


# Calculate error metrics
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("Nearest Neighbor Results:")
print(f'Mean Absolute Error (MAE): {mae:.2f}')
print(f'Mean Squared Error (MSE): {mse:.2f}')
print(f'Root Mean Squared Error (RMSE): {rmse:.2f}')

Nearest Neighbor Results:
Mean Absolute Error (MAE): 0.39
Mean Squared Error (MSE): 0.39
Root Mean Squared Error (RMSE): 0.63